name: Qbit

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List files and create directories
        run: |
          pwd && ls && mkdir -p downloads
          ls
      - name: Run Docker Container
        run: |
            docker run -t --name qbittorrent-nox --rm \
            --read-only --stop-timeout 1800 --tmpfs /tmp \
            -e QBT_LEGAL_NOTICE=put_confirm_here \
            -e QBT_WEBUI_PORT=8080 \
            -p 8080:8080 -p 6881:6881/tcp -p 6881:6881/udp \
            -v "$(pwd)/qbit/config:/config" \
            -v "$(pwd)/downloads:/downloads" \
            qbittorrentofficial/qbittorrent-nox:latest
      - name: Building Image
        run:  pip install -r requirements.txt
      - name: Building Image
        run:  python qbit.py
