name: JDDock

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List files and create directories
        run: |
          pwd && ls && mkdir -p downloads
          ls
      - name: Run Docker Container
        run: |
          docker run -d \
            --name jddoc \
            -e JD_DEVICENAME="${{ secrets.JD_DEVICENAME }}" \
            -e JD_EMAIL="${{ secrets.JD_EMAIL }}" \
            -e JD_PASSWORD="${{ secrets.JD_PASSWORD }}" \
            -v "$(pwd)/downloads:/jdownloader/downloads" \
            -v "$(pwd)/config:/jdownloader/cfg" \
            antlafarge/jdownloader:ubuntu
      - name: Building Image
        run:  docker build -t myjav .
      - name: Building Image
        run:  docker run -v "$(pwd)/downloads:/app/downloads"  myjav 
